apiVersion: v1
kind: Namespace
metadata:
  name: elasticsearch
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: bdm-2022-02
  namespace: elasticsearch
spec:
  version: 8.6.1
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: "2Gi"
              cpu: "200m"
            limits:
              memory: "2Gi"
              cpu: "1"
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: bdm-2022-02
spec:
  version: 8.6.1
  count: 1
  elasticsearchRef:
    name: bdm-2022-02
    namespace: elasticsearch
  http:
    service:
      spec:
        type: LoadBalancer
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 500Mi
      tolerations:
      - key: "restricted.app"
        operator: "Equal"
        value: "kibana"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "expected.app"
                operator: "In"
                values: ["kibana"]
