apiVersion: v1
kind: Namespace
metadata:
  name: elasticsearch
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: bdm-2022-02
  namespace: elasticsearch
spec:
  version: 8.6.1
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
      resources:
        requests:
          memory: "2Gi"
          cpu: 2
        limits:
          memory: "2Gi"
          cpu: 2

