apiVersion: v1
kind: Namespace
metadata:
  name: pgadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgadmin
  name: pgadmin
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - image: dpage/pgadmin4:5.3
        imagePullPolicy: Always
        name: pgadmin
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "brandizzi@gmail.com"
        - name: PGADMIN_CONFIG_CONSOLE_LOG_LEVEL
          value: "10"
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin-secret
              key: pgadmin-default-password
        - name: PGADMIN_PORT
          value: "80"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
      tolerations:
      - effect: NoSchedule
        key: restricted.app
        operator: Equal
        value: kibana
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: expected.app
                operator: In
                values:
                - kibana

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgadmin
  name: pgadmin
  namespace: pgadmin
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: pgadmin
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: pgadmin
type: Opaque
data:
  pgadmin-default-password: RW50cmFkYTEyMw==
