apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: bdm-2022-02-zalando
  namespace: postgresql
  labels:
    app: postgresql
spec:
  patroni:
    pg_hba:
      - local   all             all                                   trust
      - hostssl all             +zalandos    127.0.0.1/32       pam
      - host    all             all                127.0.0.1/32       md5
      - hostssl all             +zalandos    ::1/128            pam
      - host      all,replication  all  0.0.0.0/0   md5
      - host    all             all                ::1/128            md5
      - local   replication     standby                    trust
      - hostssl replication     standby all                md5
      - hostssl all             +zalandos    all                pam
      - hostssl all             all                all                md5
  teamId: "acid"
  volume:
    size: "10Gi"
  numberOfInstances: 3
  users:
    zalando:
    - superuser
    - createdb
    admin:
    - superuser
    - createdb
  databases:
    viagens: admin
  postgresql:
    version: "15"
  resources:
    requests:
      memory: "2Gi"
      cpu: "200m"
    limits:
      memory: "2Gi"
      cpu: "4"
  tolerations:
  - effect: NoSchedule
    key: restricted.app
    operator: Equal
    value: postgresql
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: expected.app
          operator: In
          values:
          - postgresql

